#######################################################################
# Server settings
#######################################################################
server:
port: 8080

######################################################################
# Spring Properties
######################################################################
spring:
  application:
    name: si-hateoas-example
  hateoas:
    use-hal-as-default-json-media-type: true